language: objective-c
osx_image: xcode10.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE="WebP.xcworkspace"
  matrix:
    - DESTINATION="OS=latest,name=iPhone X" SCHEME="WebP iOS" SDK="iphonesimulator"
    - DESTINATION="platform=OS X,arch=x86_64" SCHEME="WebP macOS" SDK="macosx10.14"
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup
before_install:
  - brew install webp
script:
  - .github/bin/test.sh
notifications:
  email: false
